### ISSUE TITLE
Certain request failures are not handle-able

### ISSUE THREAD

**Issue by dot4qu** [gajus/async-request#15]
For certain things like EADDRNOTFOUND when making requests, this package throws an Error instead of rejecting the request's promise. This makes it so anyone using the library in an async/await format cannot implement their own error handling, as it crashes the app after the user's try/catch has executed. This is an example of an error + stacktrace one gets:
```
/path/to/node_modules/async-request/src/main.js:24
                    throw new Error(error);
                    ^

Error: Error: getaddrinfo ENOTFOUND url.that.failed url.that.failed:443
    at Request.request [as _callback] (/path/to/node_modules/async-request/src/main.js:24:27)
    at self.callback (/path/to/node_modules/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.onRequestError (/path/to/node_modules/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:188:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by dot4qu** [comment]
https://github.com/gajus/async-request/pull/16

**Comment by gajus** [comment]
https://github.com/gajus/async-request#deprecated
